import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '../globals.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
          <div className="w-full h-screen flex flex-col justify-center sm:flex-row">
            <div className={`${inter.className} w-full sm:w-1/2 flex justify-center items-center`}>
              {children}
            </div>
          </div>
    );
  }
