import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '../globals.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="en">
        <body>
          <div className="w-full h-screen flex flex-col items-center justify-center sm:flex-row">
            <div className="bg-black w-full h-screen sm:w-1/2 hidden sm:flex">
              
            </div>
            <div className={`${inter.className} w-full sm:w-1/2 flex justify-center items-center`}>
              {children}
            </div>
          </div>
        </body>
      </html>
    );
  }
